### ISSUE TITLE
设置stop_time后，在获取微博时会报错

### ISSUE THREAD

**Issue by peacemo** [IshtarTang/weibo_spider#2]
**自己编译的文件在powershell中运行**
``` 
PS C:\Users\carlchen\workspace\sky\爬虫> py .\weibo_spider.py
检查配置文件
检查配置项
检查配置项兼容
配置检查完成
获取用户标识
检查运行文件
创建文件夹 ./蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)
初始化文件 ./蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)/schedule.json
初始化文件 ./蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)/download.json
初始化文件 ./蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)/result.json
初始化文件 ./蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)/r_result.json
检查完成
--------------------------------------------------------------------

要爬取的主页为：https://weibo.com/7451997786
文件标识：蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)
获取当该用户全部评论：off
其他需获取全部评论的用户id：/
自动获取新微博：off
爬取时间范围为：x - 2021-01-22 19:42
更新模式：off
更新时间范围：/

输入ok以继续
ok
开始下载
对第 1 页发起请求
15      15      15
Traceback (most recent call last):
  File "C:\Users\carlchen\workspace\sky\爬虫\weibo_spider.py", line 1456, in <module>
    download_weibo_file(config, session, schedule_filename, download_filename)
  File "C:\Users\carlchen\workspace\sky\爬虫\weibo_spider.py", line 1035, in download_weibo_file
    earliest_public_timestamp = earliest_div.xapth("//div[contains(@class,'WB_from')]/a/@date")[0]
AttributeError: 'lxml.etree._Element' object has no attribute 'xapth'
traceback.format_exc():
Traceback (most recent call last):
  File "C:\Users\carlchen\workspace\sky\爬虫\weibo_spider.py", line 1456, in <module>
    download_weibo_file(config, session, schedule_filename, download_filename)
  File "C:\Users\carlchen\workspace\sky\爬虫\weibo_spider.py", line 1035, in download_weibo_file
    earliest_public_timestamp = earliest_div.xapth("//div[contains(@class,'WB_from')]/a/@date")[0]
AttributeError: 'lxml.etree._Element' object has no attribute 'xapth'

异常中断，尝试重启程序，重启还不行就是真的有问题
窗口将于10秒后关闭
-----------------------------------
``` 
**使用你打包好的exe文件也是同样的报错**
``` 
PS C:\Users\carlchen\workspace\sky\爬虫> .\weibo_spider.exe
检查配置文件
检查配置项
检查配置项兼容
配置检查完成
获取用户标识
检查运行文件
检查完成
--------------------------------------------------------------------

要爬取的主页为：https://weibo.com/7451997786
文件标识：蓝不蓝梦日白[7451997786] (x-2021-01-22 19：42)
获取当该用户全部评论：off
其他需获取全部评论的用户id：/

自动获取新微博：off
爬取时间范围为：x - 2021-01-22 19:42

更新模式：off
更新时间范围：/

输入ok以继续
ok
开始下载
对第 1 页发起请求
15      15      15
Traceback (most recent call last):
  File "weibo_spider.py", line 1455, in <module>
    print("开始下载")
  File "weibo_spider.py", line 1029, in download_weibo_file
    # update_mode时start_time为update_start_time
AttributeError: 'lxml.etree._Element' object has no attribute 'xapth'
traceback.format_exc():
Traceback (most recent call last):
  File "weibo_spider.py", line 1455, in <module>
    print("开始下载")
  File "weibo_spider.py", line 1029, in download_weibo_file
    # update_mode时start_time为update_start_time
AttributeError: 'lxml.etree._Element' object has no attribute 'xapth'

异常中断，尝试重启程序，重启还不行就是真的有问题
窗口将于10秒后关闭
``` 

**config.json**
``` 
{
    "user_id": "7451997786",
    "all_page": 2,
    "cookies": "SINAGLOBAL=8388042601457.178.1611627745743; wvr=6; wb_view_log_7451997786=1536*8641.25; SCF=AqGoozR33lTt8iyvowHC3NG0DFyMD3Z-lRxhW4IyBWcRFo_Dk2UY3KGXREXUBIpEn_rsuYcGUH23o36hAJPrmXY.; SUB=_2A25NJU5mDeRhGeFK7lMY-SnLwzqIHXVuUziurDV8PUJbmtANLUzbkW9NQ1nbIWvKVmAXa-ePFPF_AMJCeUPULOKJ; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WWlK54ICr6aRMbO38rdzcX.5JpX5K-hUgL.FoMXSK241KMN1hq2dJLoI0qLxKnL1KeL1-BLxKBLBonL12BLxKnL1KeL1-BLxKqLBKzLBKqLxKqL1KMLBK-LxKML1K.LB.Bt; ALF=1644327327; SSOLoginState=1612791350; _s_tentry=login.sina.com.cn; UOR=cn.bing.com,www.weibo.com,login.sina.com.cn; Apache=1372267535196.8315.1612791352490; ULV=1612791352510:5:3:3:1372267535196.8315.1612791352490:1612734028374; webim_unReadCount=%7B%22time%22%3A1612791357086%2C%22dm_pub_total%22%3A5%2C%22chat_group_client%22%3A0%2C%22chat_group_notice%22%3A0%2C%22allcountNum%22%3A5%2C%22msgbox%22%3A0%7D",
    "get_all_comment": 0,
    "additional_user_ids": [],
    "auto_get_increment": 0,
    "start_time": "",
    "stop_time": "2021-01-22 19:42",
    "update_mode": 0,
    "update_start_time": "",
    "print_level": 0
  }
``` 

而且在使用毫秒级时间戳作为参数的时候，会直接提示日期格式错误
```
PS C:\Users\carlchen\workspace\sky\爬虫> .\weibo_spider.exe
检查配置文件
检查配置项
配置项 stop_time 日期格式错误
Traceback (most recent call last):
  File "weibo_spider.py", line 1319, in <module>

NameError: name 'exit' is not defined
[4936] Failed to execute script weibo_spider

// 其中 2021-01-22 19:42:01 -> 1611315721000
```

**Comment by IshtarTang** [comment]
第一个是方法名写错了已经解决了，时间格式问题我需要看一下你报错时使用的配置文件

**Comment by IshtarTang** [comment]
第一个是方法名写错了，已经解决。时间格式问题我需要看一下你报错时使用的配置文件

**Comment by IshtarTang** [comment]
刚试了下，应该是没问题的。使用时间戳作为参数应该是int类型，你是不是弄成str了
